name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull-request:
    name: Build for Node 16.13.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install dependencies
      run: npm ci
        - name: Build project
      run: npm run build
        - name: Run tests
      run: npm test