name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.13.0 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        name: Set up Node.JS version ${{ matrix.node }}
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build project
      - run: npm test
        name: Run tests