name: Node Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.JS version ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test

      - name: Publish to DockerHub
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: extiriority/college-network:latest

